version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: project_2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: weekly_salesdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo_user -d weekly_salesdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
